### ISSUE TITLE
Doesn't start anymore

### ISSUE THREAD

**Issue by afettouhi** [I-Dream-in-Code/kde-arch-update-plasmoid#30]
Pacman 5.1.0 just went into stable and the kde-arch-update-plasmoid now complains about "cannot start checkupdates". I have tried to rebuild kde-arch-update-plasmoid and the perl dependencies but still it complains.

**Comment by I-Dream-in-Code** [comment]
Checkupdates or checkupdates-aur?

Disable aur support for now

I don't have my computer with me for maybe 2 weeks

I'll get to it when it arrives

**Comment by nomis6432** [comment]
I have the same problem. In my journal I find:
`org.kde.archUpdate: Cannot start /usr/bin/checkupdates`
and when looking in /usr/bin I can only find checkupdates-aur . checkupdates is gone.
When I try to rebuild the package I get this error during the process:
`expac: error while loading shared libraries: libalpm.so.10: cannot open shared object file: No such file or directory`

The problem seems to be that pacman no longer provide ` /usr/lib/libalpm.so.10` . Instead it offers `/usr/lib/libalpm.so.11`(https://www.archlinux.org/packages/core/x86_64/pacman/files/)

That's  how far I got. Do you have a clue on what this means? I can try to fix it.

**Comment by nomis6432** [comment]
nvm I found the problem: https://www.reddit.com/r/archlinux/comments/8mu6de/notice_pacman_and_pacmancontrib_split/

`pacman-contrib` should be added to the dependencies

**Comment by afettouhi** [comment]
I can confirm this. After installing pacman-contrib and rebuild the plasmoid everything works again.

**Comment by I-Dream-in-Code** [comment]
fixed please update package
