### ISSUE TITLE
[Feature request] Clean orphan packages

### ISSUE THREAD

**Issue by navarroaxel** [I-Dream-in-Code/kde-arch-update-plasmoid#33]
Add a check option to clean no longer required packages (orphans) after upgrade.

**Comment by I-Dream-in-Code** [comment]
added

master and AUR package are updated

**Comment by navarroaxel** [comment]
Hi @I-Dream-in-Code, when I check the `clean orphan packages` checkbox the clean is not added as last step of the upgrade process. But a model opens requiring my password for made sudo changes.

![screenshot_20180814_223358](https://user-images.githubusercontent.com/1536740/44127128-410d36ac-a012-11e8-93cd-db6ab5260516.png)

I'm running the upgrade using yakuake. Which runs the same command as always 
```bash
$ aurman -Syu --noconfirm --noedit ;  echo  ; echo ---------------- ; echo Update Finished
```

**Comment by I-Dream-in-Code** [comment]
That's intended

I tried adding it before the echo but it failed to start the upgrade

The current implementation is when the window closes it cleans orphans

Feel free to submit a patch to run in the same command. 

Q process has a really nasty bug if stringing commands together via bash

I've tried various ways in other parts of the code stringing commands in one bash call and it fails to run any code in other functions

**Comment by I-Dream-in-Code** [comment]
@navarroaxel I updated the package to add confirm so it actually works

Also I asked the Qt Support about the long command bug and they said to put it in a shell script.

There's a branch called bashScript feel free to work on it.

The issue is that is runs fine in shell but when running from qprocess it unexpected EOF on the ' after -c.

Try making the stuff after -c a single string. 

Got command not found due to environment variable issues.

If you can get that working then your #34 can work too

**Comment by I-Dream-in-Code** [comment]
@navarroaxel  i got it working!!  It was huge thing to do.

I don't want to push it until i can get it working with yakuake but maybe @naraesk  can help out?

**Comment by I-Dream-in-Code** [comment]
@navarroaxel I got it all working now

@naraesk  I figured out yakuake

master and AUR package are both updated
